-- ===================================================
-- RESTAURAÇÃO COMPLETA DA TABELA PROJECTS
-- Execute este script INTEIRO no SQL Editor do Supabase
-- ===================================================

-- 1. Dropar a tabela quebrada e recriar com schema correto
DROP TABLE IF EXISTS public.projects CASCADE;

CREATE TABLE public.projects (
    id SERIAL PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    year TEXT,
    category TEXT,
    title TEXT NOT NULL,
    client TEXT,
    service TEXT,
    image TEXT,
    description TEXT,
    full_description TEXT,
    video_url TEXT,
    video_url2 TEXT,
    hover_video_url TEXT,
    video_orientation TEXT DEFAULT 'horizontal',
    gallery TEXT[],
    sort_order INTEGER DEFAULT 0
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users on projects" ON public.projects FOR SELECT USING (true);

-- 2. Inserir TODOS os 21 projetos com dados completos
INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (1, 'expo-irati-2024', '2024', 'Evento', 'DOCUMENTÁRIO EXPO IRATI 2024', 'Prefeitura de Irati', 'Eventos / Produção', '/projects/eventos/capa24EXPO01043.jpg', 'Comissionado pela Prefeitura Municipal de Irati, este documentário é o registro definitivo da ExpoIrati 2024. Nossa produção mobilizou uma estrutura técnica avançada para capturar a magnitude do evento, equilibrando a precisão do agronegócio com a energia dos grandes espetáculos. O resultado é uma narrativa audiovisual que não apenas documenta números, mas preserva a identidade cultural e o crescimento econômico da região em uma obra de alto impacto técnico e institucional.', 'Capturamos a essência e a energia da maior feira do Centro-Sul no documentário oficial da ExpoIrati 2024.', '/projects/expo-irati-2024/DOCUMENTARY_EXPO-001-006.mp4', NULL, NULL, ARRAY['/projects/eventos/24EXPO00973.jpg','/projects/eventos/24EXPO00988.jpg','/projects/eventos/24EXPO01484.jpg','/projects/eventos/24EXPO01378.jpg','/projects/eventos/24EXPO01654.jpg']::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (2, 'institucional-prefeitura-irati', '2024', 'Institucional', 'PREFEITURA DE IRATI', 'Prefeitura de Irati', 'Institucional / Vídeo', '/projects/institucional-prefeitura-irati/capa.jpg', 'Vídeo institucional horizontal para a Prefeitura de Irati.', 'Produção de vídeo institucional destacando as ações e o desenvolvimento na cidade de Irati.', '/projects/institucional-prefeitura-irati/video.mp4', NULL, '/projects/institucional-prefeitura-irati/hover.mp4', ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (3, 'aciai-institucional', '2024', 'Institucional', 'ACIAI', 'ACIAI', 'Institucional / Vídeo', '/projects/aciai-institucional/capa.jpg', 'Vídeo institucional focado no fortalecimento do comércio e indústria local.', 'Apresentação institucional horizontal produzida para a Associação Comercial e Empresarial de Irati.', '/projects/aciai-institucional/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (4, 'publicitario-via-araucaria', '2024', 'Publicitário', 'VIA ARAUCÁRIA', 'Via Araucária', 'Comercial / Horizontal', '/projects/publicitario-via-araucaria/capa.jpg', 'Peça publicitária horizontal desenvolvida para a campanha da Via Araucária.', 'Produção audiovisual com foco em conversão e awareness da marca Via Araucária.', '/projects/publicitario-via-araucaria/video.mp4', NULL, '/projects/publicitario-via-araucaria/hover.mp4', ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (5, 'publicitario-lelac-ram', '2024', 'Publicitário', 'LELAC RAM', 'Lelac Ram', 'Comercial / Vertical', '/projects/publicitario-lelac-ram/capa.jpg', 'Vídeo vertical dinâmico focado em redes sociais para a Lelac RAM.', 'Conteúdo otimizado para plataformas verticais destacando a imponência e tecnologia dos veículos RAM.', '/projects/publicitario-lelac-ram/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (6, 'publicitario-fobras-aluminio', '2024', 'Publicitário', 'FOBRAS', 'Fobras', 'Comercial / Multiplataforma', '/projects/publicitario-fobras-aluminio/capa.jpg', 'Campanha publicitária multiplataforma para a Fobras Alumínio.', 'Produção de vídeo versátil entregue tanto em formado horizontal quanto vertical para diversas mídias.', '/projects/publicitario-fobras-aluminio/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (7, 'shows-bruno-e-marrone', '2024', 'Shows', 'BRUNO E MARRONE', 'Bruno e Marrone', 'Cobertura de Show', '/projects/shows-bruno-e-marrone/capa.jpg', 'Registro emocionante e energético da apresentação da dupla Bruno e Marrone.', 'Cobertura audiovisual com múltiplas câmeras capturando a energia do público e a performance no palco.', '/projects/shows-bruno-e-marrone/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (8, 'shows-luan-pereira', '2024', 'Shows', 'LUAN PEREIRA', 'Luan Pereira', 'Cobertura de Show', '/projects/shows-luan-pereira/capa.jpg', 'Aftermovie repleto de energia do show do Luan Pereira.', 'Captura da intensa conexão entre o artista e os fãs durante todo o espetáculo com visual moderno.', NULL, NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (9, 'shows-antony-e-gabriel', '2024', 'Shows', 'ANTONY E GABRIEL', 'Antony e Gabriel', 'Cobertura de Show', '/projects/shows-antony-e-gabriel/capa-antony-gabriel-optimized.jpg', 'Cobertura audiovisual vibrante da performance sertaneja de Antony e Gabriel.', 'Apresentação musical da dupla sertaneja registrada nos detalhes dos palcos e bastidores.', '/projects/shows-antony-e-gabriel/video.mp4', NULL, '/projects/shows-antony-e-gabriel/hover.mp4', ARRAY['/projects/shows-antony-e-gabriel/6AGRIFRUT00038.jpg','/projects/shows-antony-e-gabriel/6AGRIFRUT00066.jpg','/projects/shows-antony-e-gabriel/6AGRIFRUT00103.jpg','/projects/shows-antony-e-gabriel/6AGRIFRUT00131.jpg','/projects/shows-antony-e-gabriel/6AGRIFRUT00167.jpg','/projects/shows-antony-e-gabriel/6AGRIFRUT00231.jpg','/projects/shows-antony-e-gabriel/6AGRIFRUT00271.jpg','/projects/shows-antony-e-gabriel/6AGRIFRUT00274.jpg','/projects/shows-antony-e-gabriel/6AGRIFRUT00285.jpg','/projects/shows-antony-e-gabriel/6AGRIFRUT00395.jpg']::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (10, 'shows-joao-neto-e-frederico', '2024', 'Shows', 'JOÃO NETO E FREDERICO', 'João Neto e Frederico', 'Cobertura de Show', '/projects/shows-joao-neto-e-frederico/capa-joao-neto-optimized.jpg', 'Filme de cobertura do show histórico de João Neto e Frederico.', 'Material focado no impacto do show ao vivo, com ângulos criativos e imersão entre a plateia.', '/projects/shows-joao-neto-e-frederico/video.mp4', NULL, '/projects/shows-joao-neto-e-frederico/hover.mp4', ARRAY['/projects/shows-joao-neto-e-frederico/6AGRIFRUT00476.jpg','/projects/shows-joao-neto-e-frederico/6AGRIFRUT00519.jpg','/projects/shows-joao-neto-e-frederico/6AGRIFRUT00685.jpg','/projects/shows-joao-neto-e-frederico/6AGRIFRUT00723.jpg','/projects/shows-joao-neto-e-frederico/6AGRIFRUT00742.jpg','/projects/shows-joao-neto-e-frederico/6AGRIFRUT00863-Aprimorado-NR.jpg','/projects/shows-joao-neto-e-frederico/6AGRIFRUT00902.jpg','/projects/shows-joao-neto-e-frederico/6AGRIFRUT00915.jpg']::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (11, 'shows-guilherme-e-santiago', '2024', 'Shows', 'GUILHERME E SANTIAGO', 'Guilherme e Santiago', 'Cobertura de Show', '/projects/shows-guilherme-e-santiago/capa.jpg', 'Aftermovie dinâmico destacando a apresentação memorável de Guilherme e Santiago.', 'Produção audiovisual capturando o alto astral que contagiou todo o evento.', '/projects/shows-guilherme-e-santiago/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (12, 'shows-radio-radar', '2024', 'Shows', 'RÁDIO RADAR', 'Rádio Radar', 'Cobertura', '/projects/shows-radio-radar/capa.jpg', 'Vídeo focado na Rádio Radar.', 'Registro audiovisual focado na ativação da Rádio Radar.', '/projects/shows-radio-radar/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (13, 'esporte-almeidarun', '2025', 'Esporte', 'ALMEIDA RUN', 'Almeida Run', 'Cobertura Esportiva', '/projects/esporte-almeidarun/capa.jpg', 'Cobertura vibrante da corrida Almeida Run.', 'Filme dinâmico destacando os corredores e a energia da Almeida Run 2025.', '/projects/esporte-almeidarun/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (14, 'esporte-corrida-felicidade', '2024', 'Esporte', 'CORRIDA DA FELICIDADE', 'Corrida da Felicidade', 'Cobertura Esportiva', '/projects/esporte-corrida-felicidade/capa.jpg', 'Sorrisos e superação na Corrida da Felicidade.', 'Vídeo completo cobrindo as emoções da Corrida da Felicidade.', '/projects/esporte-corrida-felicidade/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (15, 'esporte-franco-run', '2025', 'Esporte', 'FRANCO RUN', 'Franco Run', 'Cobertura Esportiva', '/projects/esporte-franco-run/capa.jpg', 'Os melhores momentos do Franco Run.', 'Vídeo oficial entregando a essência e o ritmo do Franco Run 2025.', '/projects/esporte-franco-run/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (16, 'esporte-iratrail', '2024', 'Esporte', 'IRATI TRAIL RUN', 'Irati Trail', 'Cobertura Esportiva', '/projects/esporte-iratrail/capa.jpg', 'Depoimentos e ação do Irati Trail Run.', 'Múltiplos cortes em vídeo cobrindo desde a prova na trilha até os depoimentos marcantes dos atletas no Irati Trail Run.', '/projects/esporte-iratrail/video.mp4', '/projects/esporte-iratrail/video1.mp4', '/projects/esporte-iratrail/hover.mp4', ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (17, 'esporte-proparts-sram', '2024', 'Esporte', 'PROPARTS SRAM', 'Proparts / SRAM', 'Audiovisual Esportivo', '/projects/esporte-proparts-sram/capa.jpg', 'Conteúdo institucional esportivo gravado com foco na Proparts e SRAM.', 'Peça audiovisual produzida com alta tecnologia, focada nos equipamentos esportivos e detalhes técnicos.', '/projects/esporte-proparts-sram/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (18, 'esporte-ivaskorun', '2025', 'Esporte', 'IVASKO RUN', 'Supermercados Ivasko', 'Cobertura Esportiva', '/projects/esporte-ivaskorun/capa.jpg', 'Energia total na maior corrida urbana, a Ivasko Run.', 'Série de vídeos contendo highlights e resumos detalhados de toda a experiência esportiva do Ivasko Run.', '/projects/esporte-ivaskorun/video.mp4', '/projects/esporte-ivaskorun/video1.mp4', NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (19, 'eventos-natal-irati-25', '2024', 'Evento', 'NATAL IRATI', 'Prefeitura de Irati', 'Cobertura de Evento', '/projects/eventos-natal-irati-25/capa.jpg', 'Registro vertical mágico da programação de Natal de Irati.', 'Produção de vídeo focada nos detalhes encantadores do Natal Irati, idealizado para consumo rápido em redes sociais.', '/projects/eventos-natal-irati-25/video.mp4', NULL, '/projects/eventos-natal-irati-25/hover.mp4', ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (20, 'eventos-prefeitura-imbituva-153', '2024', 'Evento', 'IMBITUVA 153 ANOS', 'Prefeitura de Imbituva', 'Institucional / Evento', '/projects/eventos-prefeitura-imbituva-153/capa.jpg', 'Filme institucional em celebração aos 153 anos do município.', 'Obra audiovisual documental e institucional registrando o marco de 153 anos da Prefeitura de Imbituva.', '/projects/eventos-prefeitura-imbituva-153/video.mp4', NULL, NULL, ARRAY[]::text[]);

INSERT INTO projects (id, slug, year, category, title, client, service, image, description, full_description, video_url, video_url2, hover_video_url, gallery) VALUES (21, 'festa-pessego-25', '2024', 'Evento', 'FESTA DO PÊSSEGO', 'Prefeitura Municipal', 'Cobertura Comercial', '/projects/festa-pessego-25/capa.jpg', 'Material oficial da Festa do Pêssego com cortes dedicados e chamadas.', 'Série de vídeos de cobertura do evento, incluindo as chamadas promocionais de sábado e os resumos de shows exclusivos.', '/projects/festa-pessego-25/video.mp4', '/projects/festa-pessego-25/video1.mp4', NULL, ARRAY[]::text[]);

-- 3. Atualizar sequence para o próximo ID
SELECT setval('projects_id_seq', 21);

-- 4. Aplicar as GALERIAS atualizadas (fotos reais dos projetos)
UPDATE projects SET gallery = ARRAY['/projects/galleries/ANTONY GABRIEL/6AGRIFRUT00190.jpg','/projects/galleries/ANTONY GABRIEL/6AGRIFRUT00231.jpg','/projects/galleries/ANTONY GABRIEL/6AGRIFRUT00234.jpg','/projects/galleries/ANTONY GABRIEL/6AGRIFRUT00271.jpg','/projects/galleries/ANTONY GABRIEL/6AGRIFRUT00318.jpg','/projects/galleries/ANTONY GABRIEL/6AGRIFRUT00334.jpg','/projects/galleries/ANTONY GABRIEL/6AGRIFRUT00364.jpg','/projects/galleries/ANTONY GABRIEL/6AGRIFRUT00395.jpg']::text[] WHERE slug = 'shows-antony-e-gabriel';

UPDATE projects SET gallery = ARRAY['/projects/galleries/BRUNO E MARRONE/153imb00171.jpg','/projects/galleries/BRUNO E MARRONE/153imb00188.jpg','/projects/galleries/BRUNO E MARRONE/153imb00204.jpg','/projects/galleries/BRUNO E MARRONE/153imb00224.jpg','/projects/galleries/BRUNO E MARRONE/153imb00236-Aprimorado-NR.jpg','/projects/galleries/BRUNO E MARRONE/153imb00248.jpg','/projects/galleries/BRUNO E MARRONE/153imb00269.jpg','/projects/galleries/BRUNO E MARRONE/153imb00283.jpg','/projects/galleries/BRUNO E MARRONE/153imb00326.jpg','/projects/galleries/BRUNO E MARRONE/153imb00379(1).jpg','/projects/galleries/BRUNO E MARRONE/153imb00398.jpg','/projects/galleries/BRUNO E MARRONE/153imb00412.jpg','/projects/galleries/BRUNO E MARRONE/153imb00421.jpg','/projects/galleries/BRUNO E MARRONE/153imb00430.jpg','/projects/galleries/BRUNO E MARRONE/153imb00527.jpg','/projects/galleries/BRUNO E MARRONE/153imb00540.jpg','/projects/galleries/BRUNO E MARRONE/153imb00546.jpg','/projects/galleries/BRUNO E MARRONE/153imb00556.jpg','/projects/galleries/BRUNO E MARRONE/153imb00564.jpg']::text[] WHERE slug = 'shows-bruno-e-marrone';

UPDATE projects SET gallery = ARRAY['/projects/galleries/EDSON HUDSON/24EXPO01198.jpg','/projects/galleries/EDSON HUDSON/24EXPO01200.jpg','/projects/galleries/EDSON HUDSON/24EXPO01259.jpg','/projects/galleries/EDSON HUDSON/24EXPO01311.jpg','/projects/galleries/EDSON HUDSON/24EXPO01327.jpg','/projects/galleries/EDSON HUDSON/24EXPO01436.jpg','/projects/galleries/EDSON HUDSON/24EXPO01459.jpg','/projects/galleries/EDSON HUDSON/24EXPO01469.jpg','/projects/galleries/EDSON HUDSON/24EXPO01473.jpg','/projects/galleries/EDSON HUDSON/24EXPO01478.jpg','/projects/galleries/EDSON HUDSON/24EXPO01479.jpg','/projects/galleries/EDSON HUDSON/24EXPO01484.jpg','/projects/galleries/EDSON HUDSON/24EXPO01489.jpg']::text[] WHERE slug = 'shows-edson-hudson';

UPDATE projects SET gallery = ARRAY['/projects/galleries/almeidarun/DJI_20250921084024_0020_D.jpg','/projects/galleries/almeidarun/DJI_20250921084048_0023_D.jpg','/projects/galleries/almeidarun/DJI_20250921084250_0030_D.jpg','/projects/galleries/almeidarun/_DSC2783.jpg','/projects/galleries/almeidarun/_DSC2803.jpg','/projects/galleries/almeidarun/_DSC2807.jpg','/projects/galleries/almeidarun/_DSC2815.jpg','/projects/galleries/almeidarun/_DSC2846.jpg','/projects/galleries/almeidarun/_DSC2888.jpg','/projects/galleries/almeidarun/_DSC2898.jpg','/projects/galleries/almeidarun/_DSC2923.jpg','/projects/galleries/almeidarun/_DSC2987.jpg','/projects/galleries/almeidarun/_DSC2995.jpg']::text[] WHERE slug = 'esporte-almeidarun';

UPDATE projects SET gallery = ARRAY['/projects/galleries/expo 24/24EXPO00455.jpg','/projects/galleries/expo 24/24EXPO00514.jpg','/projects/galleries/expo 24/24EXPO00526.jpg','/projects/galleries/expo 24/24EXPO00527.jpg','/projects/galleries/expo 24/24EXPO00639.jpg','/projects/galleries/expo 24/24EXPO00646.jpg','/projects/galleries/expo 24/24EXPO00702.jpg','/projects/galleries/expo 24/24EXPO00728.jpg','/projects/galleries/expo 24/24EXPO00753.jpg','/projects/galleries/expo 24/24EXPO00797.jpg','/projects/galleries/expo 24/24EXPO00839.jpg','/projects/galleries/expo 24/24EXPO00847.jpg','/projects/galleries/expo 24/24EXPO00864.jpg','/projects/galleries/expo 24/24EXPO00888.jpg','/projects/galleries/expo 24/24EXPO00901.jpg','/projects/galleries/expo 24/24EXPO00908.jpg','/projects/galleries/expo 24/24EXPO01043.jpg','/projects/galleries/expo 24/24EXPO01061.jpg','/projects/galleries/expo 24/24EXPO01062.jpg','/projects/galleries/expo 24/24EXPO01066.jpg','/projects/galleries/expo 24/24EXPO01193.jpg','/projects/galleries/expo 24/24EXPO01200.jpg','/projects/galleries/expo 24/24EXPO01295.jpg','/projects/galleries/expo 24/24EXPO01311.jpg','/projects/galleries/expo 24/24EXPO01371.jpg','/projects/galleries/expo 24/24EXPO01378.jpg','/projects/galleries/expo 24/24EXPO01409.jpg','/projects/galleries/expo 24/24EXPO01418.jpg','/projects/galleries/expo 24/24EXPO01571.jpg','/projects/galleries/expo 24/24EXPO01707.jpg','/projects/galleries/expo 24/24EXPO01727.jpg','/projects/galleries/expo 24/24EXPO01773.jpg','/projects/galleries/expo 24/24EXPO01891.jpg','/projects/galleries/expo 24/24EXPO01946.jpg','/projects/galleries/expo 24/24EXPO01953.jpg','/projects/galleries/expo 24/24EXPO02108.jpg','/projects/galleries/expo 24/24EXPO02317.jpg','/projects/galleries/expo 24/24EXPO02333.jpg','/projects/galleries/expo 24/24EXPO02362.jpg','/projects/galleries/expo 24/24EXPO02372.jpg','/projects/galleries/expo 24/24EXPO02401.jpg','/projects/galleries/expo 24/24EXPO02523.jpg','/projects/galleries/expo 24/24EXPO02529.jpg','/projects/galleries/expo 24/24EXPO02574.jpg','/projects/galleries/expo 24/DJI_20240821170335_0341_D.jpg','/projects/galleries/expo 24/DJI_20240823002233_0390_D.jpg','/projects/galleries/expo 24/DJI_20240824201415_0449_D.jpg','/projects/galleries/expo 24/DJI_20240825170948_0471_D.jpg','/projects/galleries/expo 24/DJI_20240825170958_0472_D.jpg','/projects/galleries/expo 24/DJI_20240825171035_0476_D.jpg']::text[] WHERE slug = 'expo-irati-2024';

UPDATE projects SET gallery = ARRAY['/projects/galleries/festa pessego/25DEL00349.jpg','/projects/galleries/festa pessego/25DEL00357.jpg','/projects/galleries/festa pessego/25DEL00384.jpg','/projects/galleries/festa pessego/25DEL00412.jpg','/projects/galleries/festa pessego/25DEL00419.jpg','/projects/galleries/festa pessego/25DEL00455.jpg','/projects/galleries/festa pessego/25DEL00494.jpg','/projects/galleries/festa pessego/25DEL00511.jpg','/projects/galleries/festa pessego/25DEL00533.jpg','/projects/galleries/festa pessego/25DEL00555.jpg','/projects/galleries/festa pessego/25DEL00561.jpg','/projects/galleries/festa pessego/25DEL00584.jpg','/projects/galleries/festa pessego/25DEL00636.jpg','/projects/galleries/festa pessego/25DEL00836.jpg','/projects/galleries/festa pessego/25DEL00892.jpg','/projects/galleries/festa pessego/25DEL00954.jpg','/projects/galleries/festa pessego/25DEL01022.jpg','/projects/galleries/festa pessego/25DEL01035.jpg','/projects/galleries/festa pessego/25DEL01134.jpg','/projects/galleries/festa pessego/25DEL01146.jpg','/projects/galleries/festa pessego/25DEL01242.jpg','/projects/galleries/festa pessego/25DEL01264.jpg','/projects/galleries/festa pessego/25DEL01281.jpg','/projects/galleries/festa pessego/25DEL01292.jpg','/projects/galleries/festa pessego/25DEL01298.jpg','/projects/galleries/festa pessego/25DEL01306.jpg','/projects/galleries/festa pessego/25DEL01410.jpg','/projects/galleries/festa pessego/25DEL01419.jpg','/projects/galleries/festa pessego/DJI_20251205184647_0081_D.jpg','/projects/galleries/festa pessego/Timeline 2_01_02_37_00-2.jpg','/projects/galleries/festa pessego/Timeline 2_01_08_59_05-2.jpg','/projects/galleries/festa pessego/Timeline 2_01_09_41_17.jpg']::text[] WHERE slug = 'festa-pessego-25';

UPDATE projects SET gallery = ARRAY['/projects/galleries/franco run/DJI_20250323080544_0348_D.jpg','/projects/galleries/franco run/DJI_20250323080734_0354_D.jpg','/projects/galleries/franco run/DJI_20250323080910_0358_D.jpg','/projects/galleries/franco run/MIR_3286.jpg','/projects/galleries/franco run/RBK_6854.jpg','/projects/galleries/franco run/RBK_6963.jpg','/projects/galleries/franco run/RBK_8068.jpg','/projects/galleries/franco run/RBK_8094.jpg','/projects/galleries/franco run/RBK_8266.jpg']::text[] WHERE slug = 'esporte-franco-run';

UPDATE projects SET gallery = ARRAY['/projects/galleries/iratrail/DELONG00019.jpg','/projects/galleries/iratrail/DELONG00021.jpg','/projects/galleries/iratrail/DELONG00022.jpg','/projects/galleries/iratrail/DELONG00024.jpg','/projects/galleries/iratrail/DELONG00025.jpg','/projects/galleries/iratrail/DJI_0608.jpg','/projects/galleries/iratrail/DJI_0653.jpg','/projects/galleries/iratrail/DJI_0760.jpg','/projects/galleries/iratrail/DJI_0836.jpg','/projects/galleries/iratrail/DJI_0889.jpg','/projects/galleries/iratrail/DJI_20251108170601_0078_D.jpg','/projects/galleries/iratrail/DJI_20251108170606_0079_D.jpg','/projects/galleries/iratrail/DJI_20251108170611_0081_D.jpg']::text[] WHERE slug = 'esporte-iratrail';

-- 5. Aplicar as imagens de Serviços corretas
UPDATE public.services
SET image = '/projects/galleries/festa pessego/25DEL00836.jpg'
WHERE number = '01';

UPDATE public.services
SET image = '/projects/galleries/expo 24/DJI_20240825170948_0471_D.jpg'
WHERE number = '02';

UPDATE public.services
SET image = '/projects/galleries/services-advertising.png'
WHERE number = '03';

UPDATE public.services
SET image = '/projects/galleries/iratrail/DJI_0653.jpg'
WHERE number = '04';

UPDATE public.services
SET image = '/projects/galleries/services-website.png'
WHERE number = '05';

-- ✅ PRONTO! Tabela projects restaurada com todos os 21 projetos + galerias + serviços
